# Generated by Django 4.2.26 on 2025-12-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('ACTS', 'Acts / Bare Laws'), ('JUDGMENTS', 'Judgments / Cases'), ('GAZETTES', 'Gazettes / Notifications'), ('NEWS', 'Legal News'), ('ARTICLES', 'Legal Articles'), ('BLOGS', 'Legal Blogs'), ('OTHERS', 'Other Legal Sources'), ('LEGAL_FORMS', 'Legal Forms'), ('REGULATIONS', 'Regulations'), ('RULES', 'Rules'), ('POLICIES', 'Policies'), ('TREATIES', 'Treaties'), ('CONTRACTS', 'Contracts / Agreements'), ('STANDARDS', 'Standards'), ('MANUALS', 'Manuals / Handbooks'), ('RECRUITMENT_NOTICES', 'Recruitment Notices'), ('GOVERNMENT_PORTAL', 'Government Portals')], default='ACTS', max_length=20)),
                ('license_info', models.JSONField(blank=True, default=dict)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'law_sources',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('document_urls', models.JSONField(blank=True, default=list, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_url_external', models.BooleanField(default=False)),
                ('saved_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('doc_content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='law_acts.source')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
    ]
