# Generated by Django 4.2.26 on 2025-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pdf_urls', models.JSONField(default=list)),
                ('is_pdf_fetched', models.BooleanField(default=False)),
                ('pdf_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Act',
                'verbose_name_plural': 'Acts',
                'db_table': 'law_acts',
            },
        ),
    ]
