# Generated by Django 4.2.26 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0002_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianKanoon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('date', models.DateField()),
                ('content', models.TextField(null=True)),
                ('is_page_url', models.BooleanField(default=False)),
                ('is_fetched', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IndianKanoon',
                'verbose_name_plural': 'IndianKanoon',
                'db_table': 'indian_kanoon',
            },
        ),
    ]
