# Generated by Django 4.2.26 on 2025-12-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0003_indiankanoon'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indiankanoon',
            index=models.Index(fields=['url', 'is_page_url'], name='ik_url_is_page_url_idx'),
        ),
    ]
