# Generated by Django 4.2.26 on 2025-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0004_indiankanoon_ik_url_is_page_url_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiankanoon',
            name='fetched_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indiankanoon',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='indiankanoon',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
