# Generated by Django 5.2.9 on 2025-12-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0005_indiankanoon_fetched_at_alter_indiankanoon_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_shortcode', models.CharField(max_length=100, unique=True)),
                ('domain_url', models.URLField(unique=True)),
                ('text_css', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('web_url', models.URLField(unique=True)),
                ('image_links', models.JSONField(default=list)),
                ('video_links', models.JSONField(default=list)),
                ('posts_links', models.JSONField(default=list)),
                ('web_content', models.TextField(null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('is_page_url', models.BooleanField(default=False)),
                ('is_content_url', models.BooleanField(default=False)),
                ('content_fetched_at', models.IntegerField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_acts.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
