# Generated by Django 5.2.9 on 2025-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0006_domain_weblinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblinks',
            name='is_content_url',
        ),
        migrations.RemoveField(
            model_name='weblinks',
            name='is_page_url',
        ),
        migrations.AddField(
            model_name='weblinks',
            name='extra_urls',
            field=models.JSONField(default=list),
        ),
    ]
