# Generated by Django 4.2.26 on 2025-12-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0007_remove_weblinks_is_content_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblinks',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='WebLinks',
        ),
    ]
