# Generated by Django 5.2.9 on 2026-01-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0008_remove_weblinks_domain_delete_domain_delete_weblinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=1024, unique=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('total_pages', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pdf_documents',
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField()),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='law_acts.pdfdocument')),
            ],
            options={
                'db_table': 'pdf_pages',
                'unique_together': {('pdf', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_index', models.IntegerField()),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('pdf_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='law_acts.pdfpage')),
            ],
            options={
                'db_table': 'pdf_images',
            },
        ),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('pdf_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='law_acts.pdfpage')),
            ],
            options={
                'db_table': 'text_chunks',
            },
        ),
    ]
