# Generated by Django 5.2.9 on 2026-01-01 15:14

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_acts', '0009_pdfdocument_pdfpage_pdfimage_textchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='textchunk',
            name='vector_embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
